### ISSUE TITLE
Instructions/rules unclear while playing the game

### ISSUE THREAD

**Issue by Thienanngvyen** [tmorris37/BeeHexed#11]
The only way to know the rules is to have the README open up while playing the game. Would be nice to have a rule card in one of the corners that can be hidden or pulled up if the player needs reference to it.

**Comment by emilyngo001** [comment]
I would like to add that when the user first launches the game, a tutorial or instruction box should pop up. You guys should have it so that there is an overview of how to play the game, with options to either go through a tutorial or skip it. Or an option for the player to read through the instructions and click ready or exit out of the screen. This is just a suggestion so feel free to ignore it, but you guys should definitely have an instruction option.

**Comment by korinX** [comment]
readme has more clear tutorial
