### ISSUE TITLE
Add Direct Download Links for Required Tools

### ISSUE THREAD

**Issue by eric-chung-swe** [tmorris37/BeeHexed#2]
It would make the set up easier and faster if the documentation include direct links to download Unity Hub and the Unity Editor to simplify the setup process for new users.

**Comment by emilyngo001** [comment]
Hi! You guys should be more specific with the 4th step of the installation "In Unity Hub, click Add -> Add project from disk, then select where you cloned the repository to add the project to Unity Hub". Maybe it's just me but it took me a bit to find where the Add button was because I was clicking through the options 😅

**Comment by korinX** [comment]
Fixed
